# Copy this to accounts.yaml and paste real session tokens.
# NEVER commit real tokens to git.

demoUser1:
  base_url: https://dev-chat-api.c64f.com/v1/chat/messages
  session_token: replace

demoUser2:
  base_url: https://dev-chat-api.c64f.com/v1/chat/messages
  session_token: replace
